apps/beltexam/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^poke$', views.poke, name='poke'),
]

apps/login/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='login'),
    url(r'^login$', views.login, name='login'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^logout$', views.logout, name='logout'),
    # url(r'^success$', views.success, name='success'),
    url(r'^admin/', admin.site.urls),
]

beltexam2Project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^beltexam/', include('apps.beltexam.urls', namespace='beltexam')),
    # url(r'^admin/', 'admin.site.urls'),
]

apps/beltexam/models.py
from __future__ import unicode_literals

from django.db import models
from ..login.models import User

# Create your models here.
class Poke(models.Model):
    poker = models.ForeignKey(User, related_name='poker')
    poked = models.ForeignKey(User, related_name='poked')

apps/beltexam/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.db.models import Count
from .models import User, Poke

# Create your views here.
def index(request):
    # allUsers = User.objects.all()
    allUsers = User.objects.annotate(num_pokes=Count('poked__poked')).exclude(id=request.session['user_id'])
    pokedYou = User.objects.filter(poker__poked = request.session['user_id']).annotate(num_pokes=Count('poker__poked')).order_by('-num_pokes')
    numPokers = len(pokedYou)
    print "#"*50
    print "pokedYou length: {}".format(len(pokedYou))


    allPokes = Poke.objects.all()

    context = {
        'users': allUsers,
        'pokedYou': pokedYou,
        'pokes': allPokes,
        'numPokers': numPokers
    }

    return render(request, 'beltexam/index.html', context)

def poke(request):
    # print "@"*50
    # print "poker_user: {}, poked_user: {}".format(request.session['user_id'], request.POST)
    poker_user = User.objects.get(id=request.session['user_id'])
    # print "poked_id: {}".format(request.POST['poked_user'])
    poked_user = User.objects.get(id=request.POST['poked_user'])
    newPoke = Poke.objects.create(poker=poker_user, poked=poked_user)


    return redirect(reverse('beltexam:index'))

apps/beltexam/templates/beltexam/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Poke-a-Friend{% endblock %}
{% block header %}
<a href="{% url 'login:logout' %}">Logout</a>
{% endblock %}
{% block pageTitle %}Poke-a-Friend{% endblock %}
{% block content %}
<h2>Welcome, {{request.session.user_name}}</h2>
<p>{{numPokers}} {{ numPokers|pluralize:"person has,people have" }} poked you!</p>
<div id="pokedYou">
    {% for poked in pokedYou %}
        <p>{{poked.first_name}} poked you {{poked.num_pokes}} time{{poked.num_pokes|pluralize}}.</p>
    {% endfor %}
</div> <!-- end pokedYou -->
<div id="userTable">
    <h2>People you may want to poke:</h2>
    <table>
        <thead>
            <tr>
                <th>Name</th><th>Alias</th><th>Email Address</th><th>Poke History</th><th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{user.first_name}}</td><td>{{user.username}}</td><td>{{user.email}}</td><td>{{user.num_pokes}} poke{{user.num_pokes|pluralize}}</td><td>
                    <form action="{% url 'beltexam:poke' %}" method='post'>
                        {% csrf_token %}
                        <input type="hidden" name='poked_user' value={{user.id}}>
                        <input type="submit" value="Poke">
                    </form></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% comment %}
<div id="pokeTable">
    <table>
        <thead>
            <tr>
                <th>Poker ID</th><th>Poke Name</th><th>Poked ID</th><th>Poked Name
            </tr>
        </thead>
        <tbody>
            {% for poke in pokes %}
            <tr>
                <td>{{poke.poker.id}}</td><td>{{poke.poker.first_name}}</td><td>{{poke.poked.id}}</td><td>{{poke.poked.first_name}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div> <!-- end pokeTable -->
{% endcomment %}
{% endblock %}